# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHlMqgvCo4-828T6_7N5bu4Iqm0en8Xs
"""

import streamlit as st
import pandas as pd
import joblib

@st.cache_data
def load_csv(path, **kwargs):
    return pd.read_csv(path, **kwargs)

@st.cache_resource
def load_pickle(path):
    return joblib.load(path)